CREATE TABLE Cities(
CityID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50))

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50))

CREATE TABLE Items(
ItemID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50),
ItemTypeID INT REFERENCES ItemTypes(ItemTypeID))

CREATE TABLE Customers(
CustomersID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50),
Birthday DATE,
CityID INT REFERENCES Cities(CityID))

CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY NOT NULL,
CustomerID INT REFERENCES Customers(CustomersID))

CREATE TABLE OrderItems(
OrderID INT REFERENCES Orders(OrderID),
ItemID INT REFERENCES Items(ItemID),
 PRIMARY KEY (OrderID, ItemID))